#!/usr/bin/env ruby

require "sxg_checker"

checker = SxgChecker::Checker.new

url = ARGV[0]

unless url
  puts "Usage:"
  puts "  sxg_checker <URL>"
  exit 1
end

document = checker.call(url)
resources = [document] + document.subresources
formatter = SxgChecker::Formatter.new
resources.each do |resource|
  puts formatter.call(resource)
end